run:
  timeout: 5m
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - exportloopref
    - gocheckcompilerdirectives
    - gofmt
    # FIXME: for some reason this errors on windows
    # - gofmt
    # - goimports
    - misspell
    - nilerr
    - unused
linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
        arguments:
          - allowList: ["^Id$", "^UserId$"]
